experiment:
  name: vgg16_experiment           # Name of the experiment run
  output_dir: results/resnet50_experiment # Directory where results will be saved
  top_k: 10
  emergency_export_enabled: true

hardware:
  use_cuda: true                    # Whether to use CUDA for acceleration
  device: cuda:0                    # Device to use (e.g., cuda:0, cpu)

model:
  name: resnet50                   # Model architecture (e.g., resnet50, vgg16)
  pretrained: true                  # Load pretrained weights
  weights_path: null             # Path to custom weights file (null to skip)
  transform: true  # Map predicted class indices to ImageNet validation label IDs

data:
  dataset_name: imagenet_val        # Name of the dataset (used for logging only)
  dataset_path: data/extracted/validation_images  # Path to images
  annotation_path: data/extracted/bounding_boxes # Path to bounding box annotations
  label_file: data/ILSVRC2012_validation_ground_truth.txt  # Path to ground truth labels
  shuffle: false                    # Shuffle data order during loading
  resize: [224, 224]                # Resize images to this size (width, height)
  # max_samples: 50                  # Maximum number of samples to process
  batch_size: 32                  # Number of samples per batch
  max_batches: 15                 # Limit number of batches processed (null for no limit)
  num_workers: 4                    # Number of workers for data loading
  pin_memory: true                  # Whether to use pinned memory (recommended with CUDA)

xai:
  name: grad_cam
  use_defaults: true
  kwargs:
    target_layer: -1

#xai:
#  name: integrated_gradients
#  use_defaults: false
#  kwargs:
#    n_steps: 100               # Höhere Genauigkeit bei akzeptabler Rechenzeit
#    internal_batch_size: 32     # Optional: gut bei GPUs mit wenig Speicher
#    multiply_by_inputs: true   # Empfohlen für interpretierbarere Attributionsmaps

metric:
  kwargs:
    {
      "iou": { "threshold": 0.3 },
      "pixel_precision_recall": { "threshold": 0.3 }
    }

visualization:
  save: true                        # Save visualizations of explanations
  show: false                       # Show visualizations during runsave_format: png
  max_visualizations: 50            # Limit number of visualizations saved (null for no limit)

logging:
  level: INFO                    # Logging level (e.g., DEBUG, INFO, WARNING)