experiment:
  name: resnet50_experiment           # Name of the experiment run
  output_dir: results/resnet50_experiment # Directory where results will be saved
  seed: 42                          # Random seed for reproducibility
  top_k: 10

hardware:
  use_cuda: true                    # Whether to use CUDA for acceleration
  device: cuda:0                    # Device to use (e.g., cuda:0, cpu)

model:
  name: resnet50                    # Model architecture (e.g., resnet50, vgg16)
  pretrained: true                  # Load pretrained weights
  weights_path: null                # Path to custom weights file (null to skip)

data:
  dataset_name: imagenet_val        # Name of the dataset (used for logging only)
  dataset_path: data/extracted/validation_images  # Path to images
  annotation_path: data/extracted/bounding_boxes # Path to bounding box annotations
  label_file: data/ILSVRC2012_validation_ground_truth.txt  # Path to ground truth labels
  shuffle: false                    # Shuffle data order during loading
  resize: [224, 224]                # Resize images to this size (width, height)
  normalize: true                   # Apply normalization to images
  augmentation:
    horizontal_flip: false          # Apply random horizontal flips during training
    random_crop: false              # Apply random crops during training
  max_samples: 200                  # Maximum number of samples to process
  batch_size: 16                  # Number of samples per batch
  max_batches: 10                  # Limit number of batches processed (null for no
  #limit)
  num_workers: 4                    # Number of workers for data loading
  pin_memory: true                  # Whether to use pinned memory (recommended with CUDA)

xai:
  name: grad_cam
  use_defaults: true
  kwargs:
    target_layer: -1

metric:
  threshold: 0.3

visualization:
  save: true                        # Save visualizations of explanations
  show: false                       # Show visualizations during run
  overlay_heatmap: true             # Overlay explanation heatmap on original images
  colormap: jet                     # Colormap to use for heatmaps (e.g., jet, viridis)
  save_format: png                  # Format for saved images (e.g., png, jpg)
  dpi: 150                          # Resolution (DPI) of saved images
  max_visualizations: 50            # Limit number of visualizations saved (null for no limit)

logging:
  level: INFO                       # Logging level (e.g., DEBUG, INFO, WARNING)